all:
  vars:
    ansible_user: johntron
    ansible_become: true
  hosts:
    nas:
      ansible_host: 192.168.1.74
    nvm:
      ansible_host: 192.168.1.76
  children:
    core:
      hosts:
        nas:
    nas:
      hosts:
        nas:
    nvr:
      hosts:
        nvm:
    docker_hosts:
      hosts: {}
    ha:
      hosts: {}
