---
all:
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
  children:
    tier1:
      hosts:
        nas-truenas:
          ansible_host: 192.168.10.10
        core-services:
          ansible_host: 192.168.10.11
        frigate:
          ansible_host: 192.168.10.12
        homeassistant:
          ansible_host: 192.168.10.13
